package chav1961.purelib.ui.interfacers;

/**
 * <p>This enumerations describes source-independent controller manipulation for the MVC-based manipulators</p> 
 * @author Alexander Chernomyrdin aka chav1961
 * @since 0.0.2
 */

public enum ControllerAction {
	EXIT, 
	REFRESH,
	COMMIT, ROLLBACK,
	GOTO_RECORD, GOTO_LIST,
	LIST_TOP, LIST_BOTTOM, LIST_ABSOLUTE, LIST_RELATIVE, 
	PAGE_TOP, PAGE_BOTTOM, PAGE_ABSOLUTE, PAGE_RELATIVE,
	COLUMN_FIRST, COLUMN_LAST, COLUMN_ABSOLUTE, COLUMN_RELATIVE,
	FIELD_FIRST, FIELD_LAST, FIELD_ABSOLUTE, FIELD_RELATIVE,
	EDIT_START, EDIT_END, EDIT_CANCEL, EDIT_SPECIAL,
	ACTION_INSERT, ACTION_DUPLICATE, ACTION_DELETE, ACTION_COMMAND,
	ACTION_SELECT, ACTION_SELECT_ALL, ACTION_UNSELECT, ACTION_UNSELECT_ALL, ACTION_INVERT_SELECTION,
	FILTER_SET, FILTER_RESET,
	ORDER_SET, ORDER_RESET
}