package chav1961.purelib.streams.interfaces.internal;

public 
enum CreoleSectionState {
	INITIAL, ORDINAL, TERMINAL, PRINT_CAPTION, PRINT_PARAGRAPH, PRINT_LIST, PRINT_LIST_ITEM, PRINT_TABLE_HEADER, PRINT_TABLE_DATA, PRINT_TABLE_DATA_END
}